# Artificial Neural Network
#### we have classification modelling here. 

### Importing the libraries

In [25]:
import numpy as np
import pandas as pd
import tensorflow as tf

## Part 1 - Data Preprocessing

### Importing the dataset

In [26]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [27]:
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [28]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [29]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [30]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [31]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [32]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [33]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### removing 1st row of dummy var. to avoid dummy variable trap

In [34]:
X = X[:, 1:]
print(X)

[[0.0 0.0 619 ... 1 1 101348.88]
 [0.0 1.0 608 ... 0 1 112542.58]
 [0.0 0.0 502 ... 1 0 113931.57]
 ...
 [0.0 0.0 709 ... 0 1 42085.58]
 [1.0 0.0 772 ... 1 0 92888.52]
 [0.0 0.0 792 ... 1 0 38190.78]]


### Feature Scaling

In [35]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [36]:
print(X)

[[-0.57873591 -0.57380915 -0.32622142 ...  0.64609167  0.97024255
   0.02188649]
 [-0.57873591  1.74273971 -0.44003595 ... -1.54776799  0.97024255
   0.21653375]
 [-0.57873591 -0.57380915 -1.53679418 ...  0.64609167 -1.03067011
   0.2406869 ]
 ...
 [-0.57873591 -0.57380915  0.60498839 ... -1.54776799  0.97024255
  -1.00864308]
 [ 1.72790383 -0.57380915  1.25683526 ...  0.64609167 -1.03067011
  -0.12523071]
 [-0.57873591 -0.57380915  1.46377078 ...  0.64609167 -1.03067011
  -1.07636976]]


### Splitting the dataset into the Training set and Test set

In [37]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Part 2 - Building the ANN

### Initializing the ANN

In [41]:
import keras

In [42]:
from keras.models import Sequential   # help to intialise ann
from keras.layers import Dense        # help to add layer in ann

In [44]:
ann = Sequential()

### Adding the input layer and the first hidden layer

In [45]:
ann.add(Dense(units=6, activation='relu', input_dim=11))

### Adding the second hidden layer

In [46]:
ann.add(Dense(units=6, activation='relu'))

### Adding the output layer

In [48]:
ann.add(Dense(units=1, activation='sigmoid'))

if we have depend var. with > 2 category say 3 categories.

then above we need to change units param(3 in that case)

& activation func would be softmax

<b>softmax</b>- sigmoid func. applied to depend. var with > 2 category.

## Training the ANN

### Compiling the ANN

#### Compiling means appying Stochastic_Gradient_Descent on whole ANN

In [49]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

optimizer- algo. to use to find optimal set of wt(s). in ann

optimizer = 'adam' mean we apply sto. grad.desc. Their are many other verison of sto. grad desc.

loss- loss func. wiithin sto.gard.desc. i.e adam modal. 
Math of adam modal require loss func. to find optimal wt.

loss func for sto.grad. in terms of logistic reg. model- logarithmic loss func required(for sigmoid act. func)

if adam algo. we need logarithmic loss func

1) if depend var. has binary o/p- then log loss func= binary_crossentropy

2) if depend var. dont've  binary o/p- then log loss func= categorical_crossentropy

Metric- citerion to evalulate model

### Training the ANN on the Training set

In [50]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
8000/8000 [==============================] - 1s 184us/step - loss: 0.5305 - accuracy: 0.7840
Epoch 2/100
8000/8000 [==============================] - 1s 80us/step - loss: 0.4656 - accuracy: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 80us/step - loss: 0.4457 - accuracy: 0.7958
Epoch 4/100
8000/8000 [==============================] - 1s 72us/step - loss: 0.4309 - accuracy: 0.8066
Epoch 5/100
8000/8000 [==============================] - 1s 78us/step - loss: 0.4209 - accuracy: 0.8167
Epoch 6/100
8000/8000 [==============================] - 1s 80us/step - loss: 0.4127 - accuracy: 0.8210
Epoch 7/100
8000/8000 [==============================] - 1s 70us/step - loss: 0.4061 - accuracy: 0.8244
Epoch 8/100
8000/8000 [==============================] - 1s 78us/step - loss: 0.4011 - accuracy: 0.8251
Epoch 9/100
8000/8000 [==============================] - 1s 79us/step - loss: 0.3967 - accuracy: 0.8264
Epoch 10/100
8000/8000 [==============================] - 1s 11

## Part 4 - Making the predictions and evaluating the model

### Predicting the Test set results

In [51]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [56]:
print(y_pred)

[[False]
 [False]
 [False]
 ...
 [False]
 [False]
 [False]]


### Making the Confusion Matrix

In [57]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1522   73]
 [ 204  201]]


In [58]:
accuracy= (1522 + 201)/(1522 + 201 + 73 + 204)
print(accuracy)

0.8615
